const KEY='promptpilot_schedules_v1'; const HKEY='promptpilot_history_v1';
const $=id=>document.getElementById(id); const load=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d)); const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let schedules=load(KEY,[]), history=load(HKEY,[]);
function render(){ $('count').textContent=schedules.length; $('empty').style.display=schedules.length?'none':'block'; $('list').innerHTML=schedules.map((s,i)=>`<div class="schedule-item"><div class="schedule-top"><div class="schedule-name">${esc(s.name)}</div><button class="delete" onclick="removeSchedule(${i})">Delete</button></div><div class="schedule-prompt">${esc(s.prompt)}</div><div class="schedule-meta"><span>◷ ${label(s)}</span><span>·</span><span>${s.enabled?'Active':'Paused'}</span></div></div>`).join(''); $('history').innerHTML=history.length?history.slice().reverse().map(h=>`<div class="history-item"><div class="history-title">${esc(h.name)}</div><div class="history-date">${new Date(h.date).toLocaleString()}</div><div class="history-result">${esc(h.result)}</div></div>`).join(''):'<div class="empty small"><p>No AI results yet.</p></div>'; }
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function label(s){if(s.frequency==='once')return `Once · ${s.time}`;if(s.frequency==='daily')return `Daily · ${s.time}`;if(s.frequency==='weekdays')return `Weekdays · ${s.time}`;return `Every ${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][Number(s.weekday)]} · ${s.time}`}
$('frequency').onchange=()=>{$('dayRow').classList.toggle('hidden',$('frequency').value!=='weekly')};
$('save').onclick=()=>{const name=$('name').value.trim()||'Untitled prompt',prompt=$('prompt').value.trim();if(!prompt){alert('Please enter a prompt.');return} schedules.push({id:crypto.randomUUID(),name,prompt,frequency:$('frequency').value,time:$('time').value,weekday:$('weekday').value,enabled:true,lastRun:null});save(KEY,schedules);$('name').value='';$('prompt').value='';render()};
window.removeSchedule=i=>{schedules.splice(i,1);save(KEY,schedules);render()};
$('clearHistory').onclick=()=>{history=[];save(HKEY,history);render()};
async function runDue(){const now=new Date(),day=now.getDay(),hh=String(now.getHours()).padStart(2,'0'),mm=String(now.getMinutes()).padStart(2,'0'),today=`${now.getFullYear()}-${now.getMonth()}-${now.getDate()}`;let changed=false;
 for(const s of schedules){if(!s.enabled||s.time!==`${hh}:${mm}`)continue;let due=s.frequency==='daily'||(s.frequency==='weekdays'&&day>=1&&day<=5)||(s.frequency==='weekly'&&day===Number(s.weekday))||(s.frequency==='once');if(!due)continue;if(s.lastRun===today)return; const result=await runAI(s.prompt); history.push({name:s.name,date:Date.now(),result});s.lastRun=today;if(s.frequency==='once')s.enabled=false;changed=true;notify(s.name,result)} if(changed){save(KEY,schedules);save(HKEY,history);render()}}
async function runAI(prompt){const key=localStorage.getItem('promptpilot_openai_key');if(!key)return `Scheduled successfully. To generate the AI answer, open browser settings and save your OpenAI API key in local storage. Prompt: ${prompt}`;try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify({model:'gpt-5.6',input:prompt})});const j=await r.json();if(!r.ok)throw new Error(j.error?.message||'API error');return j.output_text||JSON.stringify(j)}catch(e){return `AI request failed: ${e.message}`}}
function notify(title,body){if('Notification'in window&&Notification.permission==='granted')new Notification(title,{body:body.slice(0,180)});else if('Notification'in window&&Notification.permission==='default')Notification.requestPermission()}
render(); setInterval(runDue,30000); runDue();
// Set an API key from the browser console: localStorage.setItem('promptpilot_openai_key','YOUR_KEY')
