const demo=[
{id:"e1",timestamp:"2026-09-16T08:00:00Z",source:"sensor-a",type:"temperature",severity:1,entity:"motor-1",action:"observe",value:61,unit:"C"},
{id:"e2",timestamp:"2026-09-16T08:03:00Z",source:"sensor-a",type:"temperature",severity:2,entity:"motor-1",action:"observe",value:68,unit:"C"},
{id:"e3",timestamp:"2026-09-16T08:05:00Z",source:"control",type:"load",severity:1,entity:"motor-1",action:"increase",value:82,unit:"%"},
{id:"e4",timestamp:"2026-09-16T08:08:00Z",source:"sensor-a",type:"temperature",severity:3,entity:"motor-1",action:"observe",value:79,unit:"C"},
{id:"e5",timestamp:"2026-09-16T08:09:00Z",source:"control",type:"load",severity:2,entity:"motor-1",action:"throttle",value:55,unit:"%"},
{id:"e6",timestamp:"2026-09-16T08:25:00Z",source:"sensor-b",type:"vibration",severity:2,entity:"motor-1",action:"observe",value:7.2,unit:"mm/s"},
{id:"e7",timestamp:"2026-09-16T08:27:00Z",source:"sensor-b",type:"vibration",severity:2,entity:"motor-1",action:"observe",value:7.8,unit:"mm/s"}
];
let events=[];
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function normalize(raw){return raw.map((e,i)=>({id:e.id??`event-${i+1}`,timestamp:new Date(e.timestamp).toISOString(),source:e.source??'unknown',type:e.type??'unknown',severity:Number(e.severity??0),entity:e.entity??'unknown',action:e.action??'observe',value:e.value,unit:e.unit,metadata:e.metadata??{}})).filter(e=>!Number.isNaN(Date.parse(e.timestamp))).sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp));}
function analyze(list,minutes){const patterns=[];const correlations=[];const groups=new Map();list.forEach(e=>{const k=`${e.entity}|${e.type}|${e.action}`;groups.set(k,(groups.get(k)||[]).concat(e));});groups.forEach((g,k)=>{if(g.length>=3)patterns.push({title:`Repeated ${k.split('|')[1]} events`,text:`${g.length} events share entity, type, and action.`});});for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){const dt=(Date.parse(list[j].timestamp)-Date.parse(list[i].timestamp))/60000;if(dt>minutes)break;if(list[i].entity===list[j].entity&&list[i].type!==list[j].type)correlations.push({title:`Cross-signal correlation`,text:`${list[i].type} and ${list[j].type} occurred for ${list[i].entity} within ${dt.toFixed(1)} minutes.`});}return{patterns,correlations};}
function render(){const q=$('search').value.toLowerCase();const min=Number($('severity').value);const filtered=events.filter(e=>e.severity>=min&&JSON.stringify(e).toLowerCase().includes(q));const a=analyze(filtered,Math.max(1,Number($('window').value)||10));$('eventCount').textContent=filtered.length;$('sourceCount').textContent=new Set(filtered.map(e=>e.source)).size;$('patternCount').textContent=a.patterns.length;$('correlationCount').textContent=a.correlations.length;$('status').textContent=`${filtered.length} visible / ${events.length} total`;$('timeline').innerHTML=filtered.length?filtered.map(e=>`<div class="event"><time>${esc(new Date(e.timestamp).toLocaleString())}</time><div><b>${esc(e.type)} · ${esc(e.action)}</b><span class="muted">${esc(e.source)} · ${esc(e.entity)}${e.value!==undefined?` · ${esc(e.value)} ${esc(e.unit||'')}`:''}</span></div><span class="tag">S${e.severity}</span></div>`).join(''):'<p class="muted">No matching events.</p>';const obs=[...a.patterns,...a.correlations];$('observations').innerHTML=obs.length?obs.map(o=>`<div class="observation"><strong>${esc(o.title)}</strong><span class="muted">${esc(o.text)}</span></div>`).join(''):'<p class="muted">No patterns detected in the current view.</p>';}
$('loadDemo').onclick=()=>{events=normalize(demo);render()};$('search').oninput=render;$('severity').onchange=render;$('window').oninput=render;$('fileInput').onchange=async e=>{try{events=normalize(JSON.parse(await e.target.files[0].text()));render()}catch(err){alert('Invalid JSON event file.')}};$('export').onclick=()=>{const payload={generatedAt:new Date().toISOString(),events,analysis:analyze(events,Number($('window').value)||10)};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='event-intelligence-analysis.json';a.click();URL.revokeObjectURL(a.href)};
events=normalize(demo);render();
